### ISSUE TITLE
ERROR: install plugin not found verdaccio-static-access-token-middleware-plugin

### ISSUE THREAD

**Issue by pedrow-coelho** [wunderwerkio/verdaccio-static-access-token-middleware-plugin#2]
I'm trying to install the plugin in my container, but it returns the following logs error

```
error--- plugin not found. try npm install @wunderwerk/verdaccio-static-access-token-middleware-plugin 
fatal--- uncaught exception, please report this
Error: 
      @wunderwerk/verdaccio-static-access-token-middleware-plugin plugin not found. try "npm install @wunderwerk/verdaccio-static-access-token-middleware-plugin"
    at /usr/local/lib/node_modules/verdaccio/build/lib/plugin-loader.js:126:13
    at Array.map (<anonymous>)
    at loadPlugin (/usr/local/lib/node_modules/verdaccio/build/lib/plugin-loader.js:61:37)
    at defineAPI (/usr/local/lib/node_modules/verdaccio/build/api/index.js:73:45)
    at _default (/usr/local/lib/node_modules/verdaccio/build/api/index.js:112:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by chfoidl** [comment]
What is your exact setup?
Can you post your docker config or `docker-compose.yml`?

AFAIK: When using the `verdaccio/verdaccio` container, you must manually mount a folder with the installed plugin to `/verdaccio/plugins` inside the container.
You then need to replicate the `node_modules` directory structure. Therefore you should have the following directory inside the docker container: `/verdaccio/plugins/@wunderwerk/verdaccio-static-access-token-middleware-plugin`.

Inside this directory, clone the repo.
Then run `docker exec` to get a shell of your `verdaccio/verdaccio` container and navigate to this directory and run `npm install`. 

That should do the trick.
